In [31]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [32]:
df = pd.read_csv("C:/Users/akank/Desktop/Laptop_Project/data.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (893, 18)

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [33]:
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

print("\nColumns:")
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    object
 3   name               893 non-null    object
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    object
 7   CPU                893 non-null    object
 8   Ram                893 non-null    object
 9   Ram_type           893 non-null    object
 10  ROM                893 non-null    object
 11  ROM_type           893 non-null    object
 12  GPU                893 non-null    object
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    object
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), object(10)
memory usage: 125.7+ KB
None

Missing Values:
Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

Columns:
Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='object')

In [34]:
drop_cols = ['Unnamed: 0', 'Unnamed: 0.1']

for col in drop_cols:
    if col in df.columns:
        df.drop(col, axis=1, inplace=True)

df.head()

,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [35]:
print("Before:", df.shape)

df.drop_duplicates(inplace=True)

print("After:", df.shape)

Before: (893, 16)
After: (893, 16)

In [36]:
df['Ram'] = (
    df['Ram']
    .astype(str)
    .str.extract('(\d+)')
    .astype(float)
)

In [37]:
df['ROM'] = (
    df['ROM']
    .astype(str)
    .str.extract('(\d+)')
    .astype(float)
)

In [38]:
df['price'] = (
    df['price']
    .astype(str)
    .str.replace(',', '')
    .str.extract('(\d+)')
    .astype(float)
)

In [39]:
df['spec_rating'] = pd.to_numeric(
    df['spec_rating'],
    errors='coerce'
)

In [40]:
df = df.dropna(subset=['price'])

print(df.shape)

(893, 16)

In [41]:
df.head()

,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,HP,Victus 15-fb0157AX Gaming Laptop,49900.0,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8.0,DDR4,512.0,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,HP,15s-fq5007TU Laptop,39900.0,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8.0,DDR4,512.0,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,Acer,One 14 Z8-415 Laptop,26990.0,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8.0,DDR4,512.0,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729.0,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16.0,LPDDR5,512.0,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,Apple,MacBook Air 2020 MGND3HN Laptop,69990.0,69.323529,Apple M1,Octa Core (4P + 4E),8.0,DDR4,256.0,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [42]:
features = [
    'brand',
    'processor',
    'Ram',
    'OS'
]

X = df[features]

y = df['price']

In [43]:
#Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(714, 4)
(179, 4)

In [44]:
categorical_features = [
    'brand',
    'processor',
    'OS'
]

numeric_features = [
    'Ram'
]

In [45]:
#Preprocessing Pipeline
numeric_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [46]:
model_pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(
        n_estimators=200,
        random_state=42
    ))
])

In [47]:
model_pipeline.fit(X_train, y_train)

print("Training Completed")

Training Completed

In [48]:
predictions = model_pipeline.predict(X_test)

predictions[:10]

array([78830.849125  , 75501.51288149, 61959.68844719, 93929.31366667,
       65680.62103175, 57674.63432179, 40678.78104507, 59913.27022457,
       75905.79806999, 17434.45166667])

In [49]:
mae = mean_absolute_error(y_test, predictions)

rmse = np.sqrt(
    mean_squared_error(y_test, predictions)
)

r2 = r2_score(y_test, predictions)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE : 15929.562023917522
RMSE: 28496.39055772619
R2 Score: 0.7630205718308557

In [50]:
joblib.dump(
    model_pipeline,
    "laptop_price_pipeline.pkl"
)

print("Model Saved Successfully")

Model Saved Successfully

In [51]:
loaded_model = joblib.load(
    "laptop_price_pipeline.pkl"
)

sample = pd.DataFrame({
    'brand':['HP'],
    'processor':['Core i5'],
    'Ram':[16],
    'OS':['Windows']
})

price = loaded_model.predict(sample)

print("Predicted Price:", round(price[0],2))

Predicted Price: 74054.79

In [52]:
df['rating_out_of_5'] = (df['spec_rating'] / 20).round(1)

df.to_csv("laptop_recommendation_data.csv", index=False)

print("Recommendation dataset saved")

Recommendation dataset saved

In [53]:
print(df.columns.tolist())

['brand', 'name', 'price', 'spec_rating', 'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU', 'display_size', 'resolution_width', 'resolution_height', 'OS', 'warranty', 'rating_out_of_5']

In [54]:
df.to_csv("clean_laptops.csv", index=False)

In [55]:
print(df.columns.tolist())

['brand', 'name', 'price', 'spec_rating', 'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU', 'display_size', 'resolution_width', 'resolution_height', 'OS', 'warranty', 'rating_out_of_5']

In [56]:
print(df[['brand','processor','Ram','OS']].head())

    brand                      processor   Ram             OS
0      HP      5th Gen AMD Ryzen 5 5600H   8.0  Windows 11 OS
1      HP   12th Gen Intel Core i3 1215U   8.0  Windows 11 OS
2    Acer  11th Gen Intel Core i3 1115G4   8.0  Windows 11 OS
3  Lenovo   12th Gen Intel Core i5 1240P  16.0  Windows 11 OS
4   Apple                       Apple M1   8.0         Mac OS